services:
  blockchain:
    build:
      context: ./core
      dockerfile: Dockerfile
    ports:
      - "7123:7123"
    environment:
      - PORT=7123
    volumes:
      - ./core:/app
    command: npm start